# Generated by Django 5.1 on 2025-08-10 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_email_token_c6eae7_idx'), models.Index(fields=['user', 'is_used'], name='users_email_user_id_0476c8_idx'), models.Index(fields=['expires_at'], name='users_email_expires_7cc044_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('document', 'Document Verification'), ('selfie', 'Selfie Verification'), ('address', 'Address Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('provider_session_id', models.CharField(blank=True, max_length=255)),
                ('provider_verification_id', models.CharField(blank=True, max_length=255)),
                ('verification_data', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_ident_user_id_39c9bb_idx'), models.Index(fields=['verification_type', 'status'], name='users_ident_verific_8a855d_idx'), models.Index(fields=['provider_session_id'], name='users_ident_provide_497ede_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='users_phone_user_id_7d01e4_idx'), models.Index(fields=['code'], name='users_phone_code_158199_idx'), models.Index(fields=['expires_at'], name='users_phone_expires_391f20_idx')],
            },
        ),
    ]
