# Generated by Django 5.1.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='verification_level',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('basic', 'Basic'),
                    ('standard', 'Standard'),
                    ('premium', 'Premium'),
                ],
                default='basic',
                help_text='Basic: email, Standard: email+phone, Premium: email+phone+identity'
            ),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='stripe_verification_session_id',
            field=models.CharField(max_length=255, blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='stripe_verification_report_id',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='document_front_url',
            field=models.URLField(blank=True, help_text='URL to document front image'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='document_back_url',
            field=models.URLField(blank=True, help_text='URL to document back image'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='selfie_url',
            field=models.URLField(blank=True, help_text='URL to selfie image'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='document_type',
            field=models.CharField(
                max_length=50,
                blank=True,
                choices=[
                    ('passport', 'Passport'),
                    ('driving_license', 'Driving License'),
                    ('id_card', 'ID Card'),
                ],
            ),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='document_country',
            field=models.CharField(max_length=2, blank=True, help_text='ISO 3166-1 alpha-2 country code'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='risk_score',
            field=models.FloatField(null=True, blank=True, help_text='Risk score from 0 to 1'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verified',
            field=models.BooleanField(default=False, help_text='Full identity verification completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_level',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('none', 'None'),
                    ('basic', 'Basic'),
                    ('standard', 'Standard'),
                    ('premium', 'Premium'),
                ],
                default='none',
                help_text='Overall verification level based on completed verifications'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(
                default=0,
                help_text='Trust score from 0-100 based on verification completeness'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_verification_badge',
            field=models.BooleanField(default=True, help_text='Display verification badge on profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_reminder_dismissed',
            field=models.BooleanField(default=False, help_text='User dismissed verification reminder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_verification_prompt',
            field=models.DateTimeField(null=True, blank=True, help_text='Last time verification was prompted'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('verified', 'Verified'),
                    ('failed', 'Failed'),
                    ('expired', 'Expired'),
                    ('requires_input', 'Requires Input'),
                    ('canceled', 'Canceled'),
                ],
                default='pending'
            ),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='verification_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('document', 'Document Verification'),
                    ('selfie', 'Selfie Verification'),
                    ('address', 'Address Verification'),
                    ('full', 'Full Identity Verification'),
                ]
            ),
        ),
    ]