# Generated by Django 5.1 on 2025-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_enhanced_identity_verification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['stripe_verification_session_id'], name='users_ident_stripe__6c5fb1_idx'),
        ),
    ]
