# Generated by Django 5.1 on 2025-07-31 16:04

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlord_remove_property_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lease_length',
        ),
        migrations.AddField(
            model_name='property',
            name='contact_method',
            field=models.CharField(choices=[('direct', 'Direct Contact'), ('message_only', 'Message Only')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='enquiry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.CharField(blank=True, help_text="e.g., '12', '18', 'flexible'", max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(blank=True, choices=[('detached', 'Detached House'), ('semi_detached', 'Semi-Detached House'), ('terraced', 'Terraced House'), ('end_terrace', 'End of Terrace House'), ('cottage', 'Cottage'), ('bungalow', 'Bungalow'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('shared', 'Shared Accommodation'), ('studio', 'Studio'), ('room', 'Room')], max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.models.property_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
