# Generated by Django 5.1 on 2025-08-16 11:46

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='House/building number and street', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Area, townland, or district', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='eircode',
            field=models.CharField(blank=True, help_text='Irish postcode (e.g., D02 X285)', max_length=8, validators=[apps.core.models.validate_eircode]),
        ),
    ]
