# Generated by Django 5.1 on 2025-08-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_make_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate for map display', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate for map display', max_digits=10, null=True),
        ),
    ]
