# Generated by Django 5.1 on 2025-08-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_geocoding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_to',
            field=models.DateField(blank=True, help_text='End date for lease (optional)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bills_included',
            field=models.BooleanField(default=False, help_text='Are bills included in rent?'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration_type',
            field=models.CharField(blank=True, choices=[('short_term', 'Short-term (< 12 months)'), ('long_term', 'Long-term (12+ months)')], help_text='Short-term (< 12 months) or Long-term (12+ months)', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='outdoor_space',
            field=models.CharField(choices=[('none', 'None'), ('balcony', 'Balcony'), ('patio', 'Patio'), ('garden', 'Garden')], default='none', help_text='Type of outdoor space available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.CharField(choices=[('none', 'No Parking'), ('street', 'Street Parking'), ('dedicated', 'Dedicated Spot'), ('garage', 'Garage')], default='none', help_text='Type of parking available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Are pets allowed?'),
        ),
        migrations.AddField(
            model_name='property',
            name='viewing_type',
            field=models.CharField(choices=[('in_person', 'In-Person Only'), ('virtual', 'Virtual Only'), ('both', 'In-Person or Virtual')], default='both', help_text='How can the property be viewed?', max_length=20),
        ),
    ]
