# Generated by Django 5.1 on 2025-10-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_postgresql_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='core_prop_composite_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_prop_availability_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_prop_features_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_prop_active_recent_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_prop_price_beds_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='search_vector',
        ),
    ]
