# Generated by Django 5.1 on 2025-10-26 12:13

import django.contrib.postgres.search
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_property_core_prop_composite_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='core_proper_created_8d24cc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county', 'town'], name='core_proper_county__772f44_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent_monthly'], name='core_proper_rent_mo_3be6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='core_proper_bedroom_cf366a_idx'),
        ),
        # Add GIN index for full-text search on search_vector field
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='core_proper_search_vec_gin_idx'
            ),
        ),
    ]
