# Generated by Phase 4 - Performance Optimization

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_search_vector_field'),
    ]

    operations = [
        # Remove old indexes first (if they exist)
        migrations.RemoveIndex(
            model_name='property',
            name='core_property_created_a54b65_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_property_county__8ad2a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_property_rent_mo_6eea55_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_property_bedroom_e0def6_idx',
        ),
        
        # Add new optimized indexes
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', '-created_at'], name='idx_property_active_created'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county', 'is_active'], name='idx_property_county_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent_monthly', 'is_active'], name='idx_property_price_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'is_active'], name='idx_property_type_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'is_active'], name='idx_property_beds_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county', 'town'], name='idx_property_location'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_property_coords'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['ber_rating', 'is_active'], name='idx_property_ber_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['furnished', 'is_active'], name='idx_property_furnished_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['available_from', 'is_active'], name='idx_property_avail_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['pet_friendly', 'is_active'], name='idx_property_pets_active'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='idx_property_created'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent_monthly'], name='idx_property_price'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='idx_property_beds'),
        ),
        # GIN index for full-text search (PostgreSQL only)
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_property_search_gin'),
        ),
    ]
