# Generated by Django 5.1 on 2025-08-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_add_reactions_and_edit_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deletion_type',
            field=models.CharField(blank=True, choices=[('soft', 'Soft Delete'), ('hard', 'Hard Delete')], default=None, max_length=10, null=True),
        ),
    ]
