# Generated by Django 5.1 on 2025-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_fix_deletion_type_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='original_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
