# Generated by Django 5.1 on 2025-08-01 09:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_property_lease_length_property_contact_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license', models.CharField(blank=True, help_text='Business license or registration number', max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN number', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{4}\\d{6,7}([A-Z0-9]?){0,16}$')])),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('auto_reply_message', models.TextField(blank=True, help_text='Automatic reply to enquiries', max_length=500)),
                ('email_on_enquiry', models.BooleanField(default=True)),
                ('sms_on_enquiry', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=True)),
                ('allow_analytics', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='core.landlord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('enquiries', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_enquiries', models.PositiveIntegerField(default=0)),
                ('total_saves', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='core.property')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
